language: python
python:
- '3.5'
- '3.6'
before_install: pip install pipenv
install:
- pipenv install --dev
- pipenv install --dev coveralls
script:
- pipenv run make _test
- coveralls
deploy:
  provider: pypi
  user: cganterh
  password:
    secure: T9TCT4FR2R31YPueTYG/egbwhvRoYjQt0JIDcrPbfoYLmoCBwEZuBTbvTkrTZjBP5+w3qlDZrm1ZnhKMUiUZ4fbd6RQUBrv7mcGqhHMZ8Tz8uigyfHjRSmviQjgduNJ+TYVEQ2HPGXsx9ycyyZrTr+4UUiAxyvKF1/GRNjuDmHOtSpy1ypkfiljeAM4pTY+qNR3bhNGZGBMVrn00CsQHt+naLGCZXN2nygnzv9dTWzUFN7IwHVu5e7eFzp9BwskFJP/B659AFnBVNZ5ArvjYgUhvfeEAC2MgrPFa2Ap6HOeV0zk/jMU2b0DAI3/REqzrOiuhizQT5L6uz/coYOtoU85Kh6ybup4tBRVQKBVCCHE5rKIeMiK/E90kwxSBz0qG5KjCIkp7y0WBltEsj1guFAhHG0iMMnGA2kpyfw+GodGP/gTW/DvTazNHGmJZJD1ySXPivVBYhaufUGIon+lmjAUa7dd6mTO5jOHc1hDNxve4CnT0GBuAEuMNb55nLOLC+xN/9SrO3PfzOHIxuo1itwyv6NuakzkU2JDvTh8Ax0DBuiUXeSxqGiAXhCFOG5ylv3tOgBsCPeMiRIehHeWmxt5tccAScLyuCnQmHlIIQLyYXhSjQIbnnqjFzp9ZWIP7xOIC3FsgyPLlgVL6ZjIQEnEc8iVT0QpcVSkNzLrN3ZU=
  on:
    tags: true
    python: '3.5'
  distributions: "sdist bdist_wheel"
